[mypy]
python_version = 3.12
strict = True
explicit_package_bases = True
mypy_path = $MYPY_CONFIG_FILE_DIR
warn_unreachable = True

[mypy-grpc.*,jwt.*,google.protobuf.*]
ignore_missing_imports = True
