"""Canonical attestation text ``afe-attest-v1``. Aegis is the source of truth.

Mirrors ``agent-core/zone-b/aegis/src/signing/canonical.rs`` (spec section 7) byte for byte,
checked against fixtures generated by the real Aegis crate (tests/fixtures). UTF-8, every line
``\\n``-terminated, decimal integers, this exact order, NO ``order_id`` line (the client order id
is bound because Aegis sets ``order_id == signal_id``)::

    afe-attest-v1
    signal_id=<uuid>
    symbol=<SYM>
    side=<BUY|SELL|SELL_SHORT>
    order_type=<LIMIT|MARKET|STOP|STOP_LIMIT>
    qty_nanos=<int>
    limit_price_nanos=<int>
    stop_price_nanos=<int>
    decided_at_ns=<int>
    expires_at_ns=<int>
    aegis_state_seq=<int>
    limits_config_sha256=<hex>
    key_id=<string>

``payload_sha256 = SHA-256(text)``. Dev Ed25519 signs those 32 bytes; HSM ECDSA-P256 signs
the digest, i.e. verifies as ECDSA-SHA256 over the text (see ``verifiers``).
"""

from __future__ import annotations

import unicodedata
from typing import Final

from .errors import OrderValidationError

CANONICAL_VERSION: Final = "afe-attest-v1"

SIDE_BUY: Final = "BUY"
SIDE_SELL: Final = "SELL"
SIDE_SELL_SHORT: Final = "SELL_SHORT"


def _clean(name: str, value: str) -> str:
    """Same guard as Aegis: no empty value, control character or ``=`` may enter the text."""
    if not value or any(unicodedata.category(c) == "Cc" or c == "=" for c in value):
        raise OrderValidationError(f"{name} is empty or has forbidden characters")
    return value


def build_canonical_text(
    *,
    signal_id: str,
    symbol: str,
    side: str,
    order_type: str,
    qty_nanos: int,
    limit_price_nanos: int,
    stop_price_nanos: int,
    decided_at_ns: int,
    expires_at_ns: int,
    aegis_state_seq: int,
    limits_config_sha256: str,
    key_id: str,
) -> bytes:
    lines = (
        CANONICAL_VERSION,
        f"signal_id={_clean('signal_id', signal_id)}",
        f"symbol={_clean('symbol', symbol)}",
        f"side={side}",
        f"order_type={_clean('order_type', order_type)}",
        f"qty_nanos={int(qty_nanos)}",
        f"limit_price_nanos={int(limit_price_nanos)}",
        f"stop_price_nanos={int(stop_price_nanos)}",
        f"decided_at_ns={int(decided_at_ns)}",
        f"expires_at_ns={int(expires_at_ns)}",
        f"aegis_state_seq={int(aegis_state_seq)}",
        f"limits_config_sha256={_clean('limits_config_sha256', limits_config_sha256)}",
        f"key_id={_clean('key_id', key_id)}",
    )
    return ("\n".join(lines) + "\n").encode("utf-8")


def candidate_side_names(order_side: int, *, allow_short: bool) -> tuple[str, ...]:
    """Attested side names an ``OrderSide`` value may stand for (order_request.proto).

    ORDER_BUY(1) <-> BUY. ORDER_SELL(2) <-> SELL or SELL_SHORT (OrderSide has no short
    value). SELL_SHORT is only a candidate when the motor allows short selling; otherwise a
    SELL_SHORT attestation fails the digest comparison and is refused (fail closed).
    """
    if order_side == 1:
        return (SIDE_BUY,)
    if order_side == 2:
        return (SIDE_SELL, SIDE_SELL_SHORT) if allow_short else (SIDE_SELL,)
    raise OrderValidationError(f"side has unsupported value {order_side}")
